swagger: '2.0'
info:
  title: NodeJs API
  description: Handle MySQL database with Sequelize for Login and Registration
  version: 1.1.0
schemes:
  - http
basePath: /api/v1
produces:
  - application/json